version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports: ["6333:6333"]
    volumes:
      - qdrant_data:/qdrant/storage

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    ports: ["9200:9200","9600:9600"]
    volumes:
      - os_data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    depends_on: [opensearch]
    ports: ["5601:5601"]
    restart: unless-stopped

volumes:
  qdrant_data:
  os_data: