version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports: ["6334:6333"]
    volumes:
      - qdrant_data:/qdrant/storage

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    ports: ["9201:9200","9601:9600"]
    volumes:
      - os_data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    depends_on: [opensearch]
    ports: ["5602:5601"]
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-infrarag
    environment:
      POSTGRES_DB: infrarag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: infrarag_secure_pw_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-infrarag
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ChangeMe123!
    ports:
      - "5051:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  qdrant_data:
  os_data:
  postgres_data:
